services:
  db:
    image: postgres:16
    container_name: codegame-db
    environment:
      POSTGRES_USER: codegame
      POSTGRES_PASSWORD: codegame
      POSTGRES_DB: codegame
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
