[package]
name = "robotsumo"
version = "0.0.2"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
native = ["bevy/x11"]

[dependencies]
bevy.workspace = true
wasm-bindgen.workspace = true
getrandom.workspace = true
