[package]
name = "snake"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy.workspace = true
mlua.workspace = true
wasm-bindgen.workspace = true
getrandom.workspace = true
